name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Test
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2
      - name: ✨ Setup .NET 6
        uses: actions/setup-dotnet@v1
      - name: 🚚 Restore
        run: dotnet restore
      - name: 🛠️ Build
        run: dotnet build
      - name: 🧪 Test
        run: dotnet test
